### PR TITLE
[frontend] Adds scheme comparison view

### PR DESCRIPTION
**Pull request by benj-zen**
Screenshot from 2020-07-14 11-39-24

### CODE REVIEW

**Comment by dingens** [comment]
Really nice!

I like that you named encryption schemes _key exchange_. Maybe we should do this everywhere and only use `enc` internally (for folder names etc)

I don't really like that stateful is an extra column and an extra checkbox. That's so much extra info to process for that tiny bit of info that only applies to one scheme :). I'd suggest we just add a floppy icon (with tooltip) to the scheme name.

Also, I'd prefer if the table would look like this:
```
Parameter set | sizes | security | Implementation | platform | timings ... |
--------------+-------+----------+----------------+----------+-------------+
falcon1024    | 1 2 3 | 128      | ref            | intel    |  9  8  7    |
              |       |          |                | arm      | 10 11 12    | 
              |       |          | avx2           | intel    |  1  2  3    | 
              |       |          |                | arm      |  4  5  6    | 
falcon2048    | 2 4 6 | 256      | ref            | intel    | 18 17 16    | 
```


etc. That is:
- in "upper triangular form" (repeated values empty) – or, even better: spanning columns. cannot represent that in ascii art ;)
- columns ordered "down the tree" (speaking of the class model), that is, everything that is shown in one column is common to several columns to the right. Like a heading: everything to the right of the impl name column is properties of the implementation. Do you get what I mean?
- this would also have the side effect of grouping things together visually
- Parameter set, not scheme name.

Note that this suggestion is only from a user's point of view, I've not looked at the code yet.
It's obvious that it'll create some difficulty with sorting. But maybe we could at least make this triangular thing the default view and stop with it once people start sorting in ways that are incompatible or something.

Also, do you know of a simple way to make the numbers readable more easily? Either adding K/M/G suffixes (that would make comparison harder, however) or by adding tiny spaces (12 345)

**Comment by benj-zen** [comment]
> I don't really like that stateful is an extra column and an extra checkbox. That's so much extra info to process for that tiny bit of info that only applies to one scheme ;) I'd suggest we just add a floppy icon (with tooltip) to the scheme name.

Yeah, agree. I will think of something.

> in "upper triangular form"

I think this will create too much problems with sorting. There should be a possibility for sorting by e.g. private key size or verification time individually. We could however provide this as a display option where sorting is disabled. Another problem I see is that you cannot differentiate between 'grouped' and 'no data available'.

> Parameter set, not scheme name.

Ok :slightly_smiling_face: 

> Also, do you know of a simple way to make the numbers readable more easily? Either adding K/M/G suffixes (that would make comparison harder, however) or by adding tiny spaces (12 345)

I could do this in js and not in the sql query. That way we can do the sorting on the raw values but use formatted strings for the display.

> Why can one only filter for classical security?

Will add a slider for quantum.

> And should we maybe include the NIST category as well?

Will add it as an option.

**Comment by dingens** [comment]
Wow. I would have expected waaaay more code lines for this. Cool how much work a nice framework can save you.

A few more remarks:

I'd suggest we move the enc/sig switch to the very left as it's the most basic selection.

How much work would it be to store the selection in the URL for easy linking?

Also, for key exchanges, it would be cool to filter cpa/cca schemes.

**Comment by dingens** [comment]
I think that maybe we should not show sk+pk+ct ('total size'), but rather ct+pk ('communication cost' or so). It's more relevant in practice, sk size often is somehow impl dependent anyway, and communication cost is what others use for comparisons most of the time as well.

**Comment by dingens** [comment]
OK sorry, I agree with you, putting "ref impls" under "display" is confusing (and wrong: display selects columns, not rows). What do you think about putting it under "filter"? (We might save some screen space there by putting the labels besides the sliders)

I've played around with the table a little. In the screenshot below is a suggestion of how we could group things a little using backgrounds. I know it's not that easy to integrate into the results table, and it must depend on the column selection, but just from a user's perspective, what do you think?

Screenshot from 2020-07-17 18-46-41

**Comment by dingens** [comment]
"View SQL" -> "View and edit this query as SQL ..." might be easier to understand

Apart from that, I greatly appreciate your changes from today!

**Comment by benj-zen** [comment]
Thanks! I implemented your suggestions (with some small variations) as I agreed with all of them.

The table looks nice! I would address that in a follow-up PR. I you have no more comments, this can be merged.

**Pull request merged**
