### PR TITLE
Consistent descriptions

### PR DESCRIPTION
**Pull request by taudor**
Making all the descriptions consistent by transforming them into full sentences. Mainly for the welcome page of the frontend.
Also adding descriptions for gemss and mqdss.

### CODE REVIEW

**Review by dingens — APPROVED** [review]
Nice!

However I cannot say anything about the descriptions you added, can some of the others?

**Comment by dingens** [comment]
I fixed a little thing which dismissed my (approving) review, can someone else check again?

**Comment by taudor** [comment]
> Nice!
> 
> However I cannot say anything about the descriptions you added, can some of the others?

I'm not sure either...

**Review by benj-zen — APPROVED** [review]
looks good!

**Pull request merged**
