### PR TITLE
Various corrections

### PR DESCRIPTION
**Pull request by dingens**
Includes some changes to schemes, plus some "code" cleanup. You probably want to review the commits individually and not use the diff view as it contains a lot of whitespace changes which will cover up the relevant changes.

### CODE REVIEW

**Review by benj-zen — APPROVED** [review]
Thanks!

**Comment by benj-zen** [comment]
When the conflicts are resolved, this can be merged.

**Comment by taudor** [comment]
Added some blank-/newline corrections.

**Comment by dingens** [comment]
I approve tudors additions. As soon as somebody approves my merge we have 100% approval coverage ;)

**Review by taudor — APPROVED** [review]
Great teamwork :)

**Pull request merged**
