### PR TITLE
 NewHope: Update to latest scheme changes 

### PR DESCRIPTION
**Pull request by dingens**
Also adds `last_updated` field to schema

### CODE REVIEW

**Comment by benj-zen** [comment]
Did you test the `last_updated` field with enter-data-helper?

**Comment by dingens** [comment]
> Did you test the |last_updated| field with enter-data-helper?
No, should I have?

**Comment by benj-zen** [comment]
I just want to make sure that `"format": "date"` is working.

**Comment by dingens** [comment]
Ah okay, didn't think about that. Good point. I just checked, it presents a date chooser.

(Also, I did check validation—it does complain if you just enter a random string.)

**Pull request merged**
