### PR TITLE
Adds first version of the enter-data-helper

### LINKED ISSUE #15: Non-compatible attribute names
Having a `/` in attribute names is not supported by jsonforms. I suggest we change this to `|`.

### PR DESCRIPTION
**Pull request by benj-zen**
Feedback welcome.

Instructions on how to run are given here:

https://github.com/cryptoeng/pqdb/tree/enter-data/tools/enter-data-helper

Fixes #15

### CODE REVIEW

**Comment by taudor** [comment]
I've encountered some issues while using the enter-data-helper:

* I can change the name of the scheme/flavor etc. after the creation of the form. Is this intentional?
* I can't save the scheme form, the button is greyed-out.
* Somehow the flavor->type property is not saved.
* Can't save parameter sets (Getting "Error while saving file" pop-up). Same with implementations and benchmarks.
* Tooltips are great, but a little too small.

**Comment by benj-zen** [comment]
> I can change the name of the scheme/flavor etc. after the creation of the form. Is this intentional?

Yes, the name is initially set to filename but should be editable.
> I can't save the scheme form, the button is greyed-out.

This should only happen, if the current form data does not satisfy the schema.
> Somehow the flavor->type property is not saved.

Will look into it.
> Can't save parameter sets (Getting "Error while saving file" pop-up). Same with implementations and benchmarks.

Will look into it.
> Tooltips are great, but a little too small.

This is a material design issue. See https://github.com/angular/components/issues/3927.
I can try fiddling with the css.

**Comment by benj-zen** [comment]
No 3 and 4 should be fixed.

**Comment by taudor** [comment]
> > I can't save the scheme form, the button is greyed-out.
> 
> This should only happen, if the current form data does not satisfy the schema.
> 

1. Statefulness
So, apparently this is because of the `Stateful`-box. I suppose the boolean value is unset if you create a new scheme. So in order to make the `Save`-button available, you have to check and uncheck it once, if you have a non-stateful scheme. Thereafter, everything works fine.
Maybe a drop-down menu for the statefulness is a better option? Because the box also needs a `required property`-messsage. And an empty checkbox with a star next to it seems kind of weird.

2. Year
Also, is it possible to add a `required property`-message to the year (maybe just the year of the paper?).

3. Authors
The `Save`-button becomes already available after clicking the `+` for the Authors, without entering an author name.

4. Empty Strings
I can delete once entered required properties that are strings and then save the form. So I can save for example a scheme without a name. The validation tool also doesn't complain.

> No 3 and 4 should be fixed.

Thanks, are fixed. Also, tooltips look much better!

**Comment by benj-zen** [comment]
> 1. Statefulness

I will set the statefulness to false by default. This should fix it for now.

> 2. Year

This has to be changed in the schema.

> 3. Authors

This has to be changed in the schema. Right now empty strings are allowed and there is no min items restriction on the authors array.

> 4. Empty Strings

Also has to be changed in the schema. #14 is related.

**Comment by taudor** [comment]
Thanks for the clarifications.

**Pull request merged**
