### PR TITLE
Some LEDA fixes

### PR DESCRIPTION
**Pull request by dingens**
I had some uncommited changes to leda I wanted to commit to #150, but it was merged during my vacation.

Here are they. Can you review them?

### CODE REVIEW

**Comment by TomerHawk** [comment]
> I had some uncommited changes to leda I wanted to commit to #150, but it was merged during my vacation.
> 
> Here are they. Can you review them?

For sure

**Comment by TomerHawk** [comment]
Looks good

**Review by TomerHawk — APPROVED** [review]
Good work!

**Review by taudor — APPROVED** [review]
lgtm

**Pull request merged**
